# **Horizontal Stack of Arrays:**

**`Horizontal stacking`** (also called **`column-wise stacking`**) means combining two or more arrays **`side-by-side`** (i.e., along `axis=1`). It adds new columns to the right of the existing array.

It is useful when:  
* We want to combine features in machine learning.
* We have multiple 1D or 2D arrays with the same number of rows (or compatible shapes along `axis=0`).

NumPy provides the function:

```python
np.hstack((array1, array2, ...))
```

> All input arrays must have the **same number of rows** (i.e., same shape along axis=0).


**Example 1: Horizontal stacking of 1D arrays:**

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [2]:
a

array([1, 2, 3])

In [3]:
b

array([4, 5, 6])

In [4]:
result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


**Example 2: Horizontal stacking of 2D arrays:**

In [5]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
a

array([[1, 2],
       [3, 4]])

In [6]:
b

array([[5, 6],
       [7, 8]])

In [7]:
result = np.hstack((a, b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


**Equivalent using `np.concatenate`:**

We can also use `np.concatenate()` with `axis=1` for horizontal stacking:

In [8]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

| Method                        | Description                         |
| ----------------------------- | ----------------------------------- |
| `np.hstack()`                 | Stacks arrays horizontally (axis=1) |
| `np.concatenate(..., axis=1)` | Same, but more general              |